blank_issues_enabled: false


contact_links:
  - name: Feature request
    url: https://github.com/department-of-veteran-affairs/va-mobile-feature-support/issues/new?assignees=&template=feature_request.md
    about: Use this link to request a new feature in the correct repository.
    projects: ["department-of-veteran-affairs/va-mobile-feature-support"]
  
