blank_issues_enabled: false


contact_links:
  - name: Feature request
    
    about: Use this link to request a new feature in the correct repository.
    projects: ["department-of-veteran-affairs/va-mobile-feature-support"]
  
